export interface EmotionRegionData {
  id: string;
  name: string;
  description: string;
  tagline: string;
  position: [number, number, number]; // 3D center in Emotion Map landscape
  color: string;
  accentColor: string;
  fogColor: string;
  intensity: number;
  compatibleGenres: string[];
  compatibleThemes: string[];
  lightingPreset: {
    ambient: string;
    directional: string;
    pointIntensity: number;
  };
  environmentPreset: {
    particleType: 'float' | 'rain' | 'streak' | 'orbit' | 'pulse' | 'ascend' | 'drift';
    particleCount: number;
    particleSpeed: number;
    particleSize: number;
    fogDensity: number;
    glowRadius: number;
  };
  cameraPreset: {
    fov: number;
    distance: number;
  };
}

export const EMOTION_REGIONS: EmotionRegionData[] = [
  {
    id: 'wonder',
    name: 'Wonder',
    tagline: 'Infinite cosmic scale and awe-inspiring horizons',
    description: 'Expansive vistas of starlight, floating luminescent motes, and a breathless sense of discovery.',
    position: [-16, 8, -20],
    color: '#60a5fa',
    accentColor: '#3b82f6',
    fogColor: '#030712',
    intensity: 0.9,
    compatibleGenres: ['Sci-Fi', 'Adventure', 'Fantasy', 'Documentary'],
    compatibleThemes: ['Cosmic Mystery', 'Space Exploration', 'Human Curiosity', 'Time & Relativity'],
    lightingPreset: {
      ambient: '#1e3a8a',
      directional: '#93c5fd',
      pointIntensity: 2.8,
    },
    environmentPreset: {
      particleType: 'float',
      particleCount: 600,
      particleSpeed: 0.02,
      particleSize: 0.28,
      fogDensity: 0.012,
      glowRadius: 18,
    },
    cameraPreset: { fov: 60, distance: 24 },
  },
  {
    id: 'melancholy',
    name: 'Melancholy',
    tagline: 'Poetic blue stillness and reflective quiet',
    description: 'Soft blue-gray fog, gentle falling rain particles, and lingering quiet resonance.',
    position: [16, -4, -22],
    color: '#94a3b8',
    accentColor: '#64748b',
    fogColor: '#0f172a',
    intensity: 0.65,
    compatibleGenres: ['Drama', 'Indie', 'Romance', 'Mystery'],
    compatibleThemes: ['Solitude', 'Memory & Loss', 'Unspoken Bonds', 'Healing'],
    lightingPreset: {
      ambient: '#0f172a',
      directional: '#cbd5e1',
      pointIntensity: 1.4,
    },
    environmentPreset: {
      particleType: 'rain',
      particleCount: 500,
      particleSpeed: 0.04,
      particleSize: 0.18,
      fogDensity: 0.022,
      glowRadius: 16,
    },
    cameraPreset: { fov: 48, distance: 20 },
  },
  {
    id: 'adrenaline',
    name: 'Adrenaline',
    tagline: 'Kinetic velocity and high-stakes momentum',
    description: 'Dynamic light trails, high particle speed, and visceral pulsing energy.',
    position: [-18, -10, -26],
    color: '#f87171',
    accentColor: '#ef4444',
    fogColor: '#180505',
    intensity: 1.0,
    compatibleGenres: ['Action', 'Thriller', 'Crime', 'Sci-Fi'],
    compatibleThemes: ['Survival Under Pressure', 'High Stakes Pursuit', 'Rebellion'],
    lightingPreset: {
      ambient: '#450a0a',
      directional: '#fca5a5',
      pointIntensity: 3.5,
    },
    environmentPreset: {
      particleType: 'streak',
      particleCount: 700,
      particleSpeed: 0.1,
      particleSize: 0.32,
      fogDensity: 0.01,
      glowRadius: 20,
    },
    cameraPreset: { fov: 68, distance: 18 },
  },
  {
    id: 'comfort',
    name: 'Comfort',
    tagline: 'Warm sanctuary and tranquil golden ease',
    description: 'Warm amber glow, soft drifting dust motes, and comforting familiar warmth.',
    position: [18, 10, -18],
    color: '#fde047',
    accentColor: '#eab308',
    fogColor: '#1a1305',
    intensity: 0.55,
    compatibleGenres: ['Comedy', 'Animation', 'Drama', 'Family'],
    compatibleThemes: ['Found Family', 'Simple Pleasures', 'Self-Discovery', 'Warmth'],
    lightingPreset: {
      ambient: '#2e1804',
      directional: '#fef08a',
      pointIntensity: 2.0,
    },
    environmentPreset: {
      particleType: 'drift',
      particleCount: 450,
      particleSpeed: 0.015,
      particleSize: 0.22,
      fogDensity: 0.016,
      glowRadius: 15,
    },
    cameraPreset: { fov: 50, distance: 19 },
  },
  {
    id: 'tension',
    name: 'Tension',
    tagline: 'Edge-of-seat suspense and shadowy depth',
    description: 'Narrow beams of violet light, deep abyssal shadows, and rhythmic pulse waves.',
    position: [-8, -14, -24],
    color: '#a855f7',
    accentColor: '#9333ea',
    fogColor: '#0c0414',
    intensity: 0.95,
    compatibleGenres: ['Psychological Thriller', 'Horror', 'Mystery', 'Crime'],
    compatibleThemes: ['Paranoia & Deception', 'Unseen Threats', 'Moral Dilemmas'],
    lightingPreset: {
      ambient: '#1e1b4b',
      directional: '#c084fc',
      pointIntensity: 3.0,
    },
    environmentPreset: {
      particleType: 'pulse',
      particleCount: 550,
      particleSpeed: 0.06,
      particleSize: 0.2,
      fogDensity: 0.028,
      glowRadius: 17,
    },
    cameraPreset: { fov: 52, distance: 21 },
  },
  {
    id: 'joy',
    name: 'Joy',
    tagline: 'Radiant optimism and euphoric light',
    description: 'Vibrant golden particles rising upward with buoyant, triumphant energy.',
    position: [8, 14, -20],
    color: '#fbbf24',
    accentColor: '#f59e0b',
    fogColor: '#1c1303',
    intensity: 0.85,
    compatibleGenres: ['Musical', 'Comedy', 'Animation', 'Adventure'],
    compatibleThemes: ['Celebration of Life', 'Playful Wonder', 'Friendship', 'Triumph'],
    lightingPreset: {
      ambient: '#3a2002',
      directional: '#fef08a',
      pointIntensity: 3.2,
    },
    environmentPreset: {
      particleType: 'ascend',
      particleCount: 650,
      particleSpeed: 0.05,
      particleSize: 0.28,
      fogDensity: 0.011,
      glowRadius: 19,
    },
    cameraPreset: { fov: 58, distance: 22 },
  },
  {
    id: 'nostalgia',
    name: 'Nostalgia',
    tagline: 'Analog warmth and sepia memory texture',
    description: 'Analog film grain atmosphere, warm amber hues, and soft lingering frames.',
    position: [-12, 12, -16],
    color: '#fb923c',
    accentColor: '#f97316',
    fogColor: '#170c04',
    intensity: 0.7,
    compatibleGenres: ['Coming-of-Age', 'Drama', 'Romance', 'Historical'],
    compatibleThemes: ['Passing of Time', 'Childhood Memories', 'Lost Innocence'],
    lightingPreset: {
      ambient: '#2a1403',
      directional: '#fed7aa',
      pointIntensity: 2.1,
    },
    environmentPreset: {
      particleType: 'float',
      particleCount: 480,
      particleSpeed: 0.018,
      particleSize: 0.24,
      fogDensity: 0.018,
      glowRadius: 16,
    },
    cameraPreset: { fov: 48, distance: 20 },
  },
  {
    id: 'hope',
    name: 'Hope',
    tagline: 'Dawn light breaking across the horizon',
    description: 'Gradual dawn light illuminating dark void as ascending motes rise upward.',
    position: [0, -16, -28],
    color: '#38bdf8',
    accentColor: '#0284c7',
    fogColor: '#05131e',
    intensity: 0.8,
    compatibleGenres: ['Drama', 'Biography', 'Sci-Fi', 'Adventure'],
    compatibleThemes: ['Overcoming Odds', 'Human Resilience', 'New Beginnings'],
    lightingPreset: {
      ambient: '#0c2a40',
      directional: '#bae6fd',
      pointIntensity: 2.8,
    },
    environmentPreset: {
      particleType: 'ascend',
      particleCount: 620,
      particleSpeed: 0.035,
      particleSize: 0.25,
      fogDensity: 0.015,
      glowRadius: 18,
    },
    cameraPreset: { fov: 55, distance: 25 },
  },
  {
    id: 'mystery',
    name: 'Mystery',
    tagline: 'Twilight fog and enigmatic hidden depths',
    description: 'Deep violet fog veil with slowly rotating luminescent rings and hidden orbits.',
    position: [0, 16, -26],
    color: '#818cf8',
    accentColor: '#4f46e5',
    fogColor: '#090918',
    intensity: 0.85,
    compatibleGenres: ['Mystery', 'Neo-Noir', 'Crime', 'Sci-Fi'],
    compatibleThemes: ['Uncovering Truth', 'Hidden Secrets', 'Complex Puzzles'],
    lightingPreset: {
      ambient: '#12123b',
      directional: '#c7d2fe',
      pointIntensity: 2.5,
    },
    environmentPreset: {
      particleType: 'orbit',
      particleCount: 580,
      particleSpeed: 0.025,
      particleSize: 0.23,
      fogDensity: 0.025,
      glowRadius: 17,
    },
    cameraPreset: { fov: 52, distance: 23 },
  },
  {
    id: 'romance',
    name: 'Romance',
    tagline: 'Ethereal rose quartz luminescence',
    description: 'Drifting blush motes, gentle intimate backlighting, and delicate emotional depth.',
    position: [-20, 2, -22],
    color: '#f472b6',
    accentColor: '#db2777',
    fogColor: '#17030e',
    intensity: 0.75,
    compatibleGenres: ['Romance', 'Romantic Comedy', 'Drama', 'Fantasy'],
    compatibleThemes: ['Intimate Attraction', 'Fate & Destiny', 'Emotional Vulnerability'],
    lightingPreset: {
      ambient: '#3a0822',
      directional: '#fbcfe8',
      pointIntensity: 2.3,
    },
    environmentPreset: {
      particleType: 'orbit',
      particleCount: 500,
      particleSpeed: 0.02,
      particleSize: 0.24,
      fogDensity: 0.018,
      glowRadius: 16,
    },
    cameraPreset: { fov: 50, distance: 21 },
  },
  {
    id: 'fear',
    name: 'Fear',
    tagline: 'Abyssal shadow and dark crimson dread',
    description: 'Dark crimson aura, erratic pulse ripples, and claustrophobic spatial depth.',
    position: [20, -12, -28],
    color: '#f43f5e',
    accentColor: '#e11d48',
    fogColor: '#140206',
    intensity: 0.9,
    compatibleGenres: ['Horror', 'Supernatural', 'Thriller'],
    compatibleThemes: ['The Unknown', 'Isolation & Dread', 'Loss of Control'],
    lightingPreset: {
      ambient: '#31040d',
      directional: '#fecdd3',
      pointIntensity: 2.2,
    },
    environmentPreset: {
      particleType: 'pulse',
      particleCount: 520,
      particleSpeed: 0.07,
      particleSize: 0.22,
      fogDensity: 0.032,
      glowRadius: 18,
    },
    cameraPreset: { fov: 46, distance: 19 },
  },
  {
    id: 'reflection',
    name: 'Reflection',
    tagline: 'Crystalline contemplative quiet',
    description: 'Deep indigo mirror plane, stillness, and meditative rhythmic pulses.',
    position: [12, -12, -18],
    color: '#38bdf8',
    accentColor: '#0284c7',
    fogColor: '#030e17',
    intensity: 0.65,
    compatibleGenres: ['Drama', 'Art House', 'Philosophical'],
    compatibleThemes: ['Existential Questions', 'Self-Examination', 'Silence'],
    lightingPreset: {
      ambient: '#082f49',
      directional: '#bae6fd',
      pointIntensity: 1.6,
    },
    environmentPreset: {
      particleType: 'float',
      particleCount: 420,
      particleSpeed: 0.01,
      particleSize: 0.2,
      fogDensity: 0.02,
      glowRadius: 15,
    },
    cameraPreset: { fov: 46, distance: 22 },
  },
];
