export interface EmotionData {
  id: string;
  name: string;
  tagline: string;
  description: string;
  color: string;
  accentColor: string;
  fogColor: string;
  intensity: number; // 0.1 to 1.0
  position: [number, number, number];
  atmosphere: {
    fogDensity: number;
    blurAmount: number;
    bloomIntensity: number;
  };
  lightingPreset: {
    ambient: string;
    directional: string;
    pointIntensity: number;
  };
  particlePreset: {
    count: number;
    speed: number;
    size: number;
    motionType: 'float' | 'rain' | 'streak' | 'orbit' | 'pulse' | 'ascend' | 'drift';
    color: string;
  };
  cameraPreset: {
    fov: number;
    distance: number;
    damping: number;
  };
  compatibleGenres: string[];
  compatibleThemes: string[];
  compatiblePacing: 'Slow' | 'Moderate' | 'Fast' | 'Unpredictable';
  compatibleVisualStyles: string[];
}

export const EMOTIONS: EmotionData[] = [
  {
    id: 'wonder',
    name: 'Wonder',
    tagline: 'Awe-inspiring vistas and vast cosmic scale',
    description: 'Expansive starfields, slow-moving light, and a breathtaking sense of infinite depth.',
    color: '#60a5fa',
    accentColor: '#3b82f6',
    fogColor: '#030712',
    intensity: 0.9,
    position: [-12, 4, -15],
    atmosphere: {
      fogDensity: 0.015,
      blurAmount: 2,
      bloomIntensity: 1.5,
    },
    lightingPreset: {
      ambient: '#1e3a8a',
      directional: '#93c5fd',
      pointIntensity: 2.5,
    },
    particlePreset: {
      count: 1200,
      speed: 0.02,
      size: 0.25,
      motionType: 'float',
      color: '#bfdbfe',
    },
    cameraPreset: {
      fov: 60,
      distance: 28,
      damping: 0.05,
    },
    compatibleGenres: ['Sci-Fi', 'Adventure', 'Fantasy', 'Documentary'],
    compatibleThemes: ['Space Exploration', 'Cosmic Mystery', 'Human Curiosity', 'Time & Relativity'],
    compatiblePacing: 'Slow',
    compatibleVisualStyles: ['Monumental Geometry', 'Anamorphic Lens Flares', 'Deep Cosmic Contrast'],
  },
  {
    id: 'melancholy',
    name: 'Melancholy',
    tagline: 'Poetic stillness and quiet blue reflection',
    description: 'Slow rain-like particles, soft blue-gray atmosphere, and distant lingering light.',
    color: '#94a3b8',
    accentColor: '#64748b',
    fogColor: '#0f172a',
    intensity: 0.6,
    position: [12, -2, -18],
    atmosphere: {
      fogDensity: 0.025,
      blurAmount: 4,
      bloomIntensity: 0.8,
    },
    lightingPreset: {
      ambient: '#0f172a',
      directional: '#cbd5e1',
      pointIntensity: 1.2,
    },
    particlePreset: {
      count: 900,
      speed: 0.04,
      size: 0.18,
      motionType: 'rain',
      color: '#94a3b8',
    },
    cameraPreset: {
      fov: 45,
      distance: 22,
      damping: 0.03,
    },
    compatibleGenres: ['Drama', 'Indie', 'Romance', 'Mystery'],
    compatibleThemes: ['Solitude', 'Memory & Regret', 'Unspoken Bonds', 'Loss & Healing'],
    compatiblePacing: 'Slow',
    compatibleVisualStyles: ['Desaturated Palettes', 'Soft Diffusion Filter', 'Static Framing'],
  },
  {
    id: 'adrenaline',
    name: 'Adrenaline',
    tagline: 'High-octane momentum and raw kinetic energy',
    description: 'Faster particle velocity, dynamic light streaks, and subtle camera acceleration.',
    color: '#f87171',
    accentColor: '#ef4444',
    fogColor: '#180505',
    intensity: 1.0,
    position: [-15, -6, -22],
    atmosphere: {
      fogDensity: 0.01,
      blurAmount: 1,
      bloomIntensity: 2.2,
    },
    lightingPreset: {
      ambient: '#450a0a',
      directional: '#fca5a5',
      pointIntensity: 3.5,
    },
    particlePreset: {
      count: 1500,
      speed: 0.12,
      size: 0.3,
      motionType: 'streak',
      color: '#fca5a5',
    },
    cameraPreset: {
      fov: 70,
      distance: 18,
      damping: 0.1,
    },
    compatibleGenres: ['Action', 'Thriller', 'Crime', 'Sci-Fi'],
    compatibleThemes: ['Survival Under Pressure', 'High Stakes Pursuit', 'Rebellion', 'Time-Critical Missions'],
    compatiblePacing: 'Fast',
    compatibleVisualStyles: ['Handheld Kinetic Movement', 'High Contrast Neon', 'Rapid Cuts'],
  },
  {
    id: 'comfort',
    name: 'Comfort',
    tagline: 'Warm sanctuary and gentle soothing light',
    description: 'Warm amber ambient glow, soft floating motes, and tranquil atmospheric ease.',
    color: '#fde047',
    accentColor: '#eab308',
    fogColor: '#1a1305',
    intensity: 0.5,
    position: [14, 6, -14],
    atmosphere: {
      fogDensity: 0.018,
      blurAmount: 3,
      bloomIntensity: 1.1,
    },
    lightingPreset: {
      ambient: '#2e1804',
      directional: '#fef08a',
      pointIntensity: 1.8,
    },
    particlePreset: {
      count: 750,
      speed: 0.015,
      size: 0.22,
      motionType: 'drift',
      color: '#fef08a',
    },
    cameraPreset: {
      fov: 50,
      distance: 20,
      damping: 0.02,
    },
    compatibleGenres: ['Comedy', 'Animation', 'Drama', 'Family'],
    compatibleThemes: ['Found Family', 'Simple Pleasures', 'Self-Discovery', 'Warm Nostalgia'],
    compatiblePacing: 'Moderate',
    compatibleVisualStyles: ['Golden Hour Lighting', 'Tactile Warmth', 'Gentle Tracking Shots'],
  },
  {
    id: 'tension',
    name: 'Tension',
    tagline: 'Edge-of-seat suspense and subtle looming shadows',
    description: 'Narrow laser-like shafts of light, deep abyssal shadows, and rhythmic pulse waves.',
    color: '#a855f7',
    accentColor: '#9333ea',
    fogColor: '#0c0414',
    intensity: 0.95,
    position: [-6, -10, -20],
    atmosphere: {
      fogDensity: 0.03,
      blurAmount: 2,
      bloomIntensity: 1.8,
    },
    lightingPreset: {
      ambient: '#1e1b4b',
      directional: '#c084fc',
      pointIntensity: 2.8,
    },
    particlePreset: {
      count: 1000,
      speed: 0.06,
      size: 0.2,
      motionType: 'pulse',
      color: '#e9d5ff',
    },
    cameraPreset: {
      fov: 52,
      distance: 22,
      damping: 0.07,
    },
    compatibleGenres: ['Psychological Thriller', 'Horror', 'Mystery', 'Crime'],
    compatibleThemes: ['Paranoia & Deception', 'Unseen Threats', 'Moral Dilemmas', 'Tight Spaces'],
    compatiblePacing: 'Unpredictable',
    compatibleVisualStyles: ['Claustrophobic Framing', 'Low-Key Chiaroscuro', 'Eerie Slow Zooms'],
  },
  {
    id: 'joy',
    name: 'Joy',
    tagline: 'Radiant optimism and euphoric light bursts',
    description: 'Vibrant golden-amber particles, upward buoyancy, and brilliant uplifting aura.',
    color: '#fbbf24',
    accentColor: '#f59e0b',
    fogColor: '#1c1303',
    intensity: 0.85,
    position: [6, 10, -16],
    atmosphere: {
      fogDensity: 0.012,
      blurAmount: 1.5,
      bloomIntensity: 2.0,
    },
    lightingPreset: {
      ambient: '#3a2002',
      directional: '#fef08a',
      pointIntensity: 3.0,
    },
    particlePreset: {
      count: 1100,
      speed: 0.05,
      size: 0.28,
      motionType: 'ascend',
      color: '#fef08a',
    },
    cameraPreset: {
      fov: 58,
      distance: 24,
      damping: 0.04,
    },
    compatibleGenres: ['Musical', 'Comedy', 'Animation', 'Adventure'],
    compatibleThemes: ['Celebration of Life', 'Triumph of Spirit', 'Playful Wonder', 'Friendship'],
    compatiblePacing: 'Fast',
    compatibleVisualStyles: ['Saturated Palette', 'Sweeping Crane Shots', 'Dynamic Lighting'],
  },
  {
    id: 'nostalgia',
    name: 'Nostalgia',
    tagline: 'Analog warmth, sepia memories, and gentle grain',
    description: 'Analog film grain effect, warm vintage amber hues, and soft frame flicker.',
    color: '#fb923c',
    accentColor: '#f97316',
    fogColor: '#170c04',
    intensity: 0.7,
    position: [-8, 8, -12],
    atmosphere: {
      fogDensity: 0.02,
      blurAmount: 3.5,
      bloomIntensity: 1.3,
    },
    lightingPreset: {
      ambient: '#2a1403',
      directional: '#fed7aa',
      pointIntensity: 1.9,
    },
    particlePreset: {
      count: 850,
      speed: 0.02,
      size: 0.24,
      motionType: 'float',
      color: '#ffedd5',
    },
    cameraPreset: {
      fov: 48,
      distance: 21,
      damping: 0.03,
    },
    compatibleGenres: ['Coming-of-Age', 'Drama', 'Romance', 'Historical'],
    compatibleThemes: ['Passing of Time', 'Childhood Memories', 'Lost Innocence', 'Reconnection'],
    compatiblePacing: 'Slow',
    compatibleVisualStyles: ['35mm Film Texture', 'Hazy Soft Focus', 'Vintage Color Grades'],
  },
  {
    id: 'hope',
    name: 'Hope',
    tagline: 'Emerging light breaking through dark horizon',
    description: 'Glow gradually illuminating the void, particles floating upward toward a dawn.',
    color: '#38bdf8',
    accentColor: '#0284c7',
    fogColor: '#05131e',
    intensity: 0.8,
    position: [0, -12, -25],
    atmosphere: {
      fogDensity: 0.016,
      blurAmount: 2.2,
      bloomIntensity: 1.9,
    },
    lightingPreset: {
      ambient: '#0c2a40',
      directional: '#bae6fd',
      pointIntensity: 2.7,
    },
    particlePreset: {
      count: 1300,
      speed: 0.035,
      size: 0.25,
      motionType: 'ascend',
      color: '#e0f2fe',
    },
    cameraPreset: {
      fov: 55,
      distance: 26,
      damping: 0.04,
    },
    compatibleGenres: ['Drama', 'Biography', 'Sci-Fi', 'Adventure'],
    compatibleThemes: ['Overcoming Adversity', 'Human Resilience', 'New Beginnings', 'Faith in Humanity'],
    compatiblePacing: 'Moderate',
    compatibleVisualStyles: ['Sunrise Silhouettes', 'Uplifting Lens Flares', 'Expansive Panoramas'],
  },
  {
    id: 'fear',
    name: 'Fear',
    tagline: 'Deep abyssal shadows and primal psychological dread',
    description: 'Eerie dark crimson aura, erratic pulse ripples, and claustrophobic spatial depth.',
    color: '#f43f5e',
    accentColor: '#e11d48',
    fogColor: '#140206',
    intensity: 0.9,
    position: [16, -10, -24],
    atmosphere: {
      fogDensity: 0.035,
      blurAmount: 3,
      bloomIntensity: 1.4,
    },
    lightingPreset: {
      ambient: '#31040d',
      directional: '#fecdd3',
      pointIntensity: 2.0,
    },
    particlePreset: {
      count: 950,
      speed: 0.08,
      size: 0.22,
      motionType: 'pulse',
      color: '#ffe4e6',
    },
    cameraPreset: {
      fov: 46,
      distance: 19,
      damping: 0.08,
    },
    compatibleGenres: ['Horror', 'Supernatural', 'Thriller', 'Sci-Fi Horror'],
    compatibleThemes: ['The Unknown', 'Isolation & Dread', 'Supernatural Presence', 'Loss of Control'],
    compatiblePacing: 'Unpredictable',
    compatibleVisualStyles: ['Strobe & Darkness', 'Deep Shadow Contrast', 'Disorienting Angles'],
  },
  {
    id: 'romance',
    name: 'Romance',
    tagline: 'Soft rose quartz luminescence and intimate connection',
    description: 'Drifting blush motes, gentle intimate lighting, and ethereal romantic depth.',
    color: '#f472b6',
    accentColor: '#db2777',
    fogColor: '#17030e',
    intensity: 0.75,
    position: [-16, 2, -19],
    atmosphere: {
      fogDensity: 0.02,
      blurAmount: 3,
      bloomIntensity: 1.6,
    },
    lightingPreset: {
      ambient: '#3a0822',
      directional: '#fbcfe8',
      pointIntensity: 2.2,
    },
    particlePreset: {
      count: 900,
      speed: 0.02,
      size: 0.24,
      motionType: 'orbit',
      color: '#fce7f3',
    },
    cameraPreset: {
      fov: 50,
      distance: 21,
      damping: 0.03,
    },
    compatibleGenres: ['Romance', 'Romantic Comedy', 'Drama', 'Fantasy'],
    compatibleThemes: ['Intimate Attraction', 'Fate & Destiny', 'Emotional Vulnerability', 'Longing'],
    compatiblePacing: 'Moderate',
    compatibleVisualStyles: ['Shallow Depth of Field', 'Soft Backlighting', 'Warm Pastel Tones'],
  },
  {
    id: 'mystery',
    name: 'Mystery',
    tagline: 'Enigmatic twilight fog and hidden secrets',
    description: 'Veil of deep violet fog, slowly turning luminescent rings, and subtle enigmatic orbits.',
    color: '#818cf8',
    accentColor: '#4f46e5',
    fogColor: '#090918',
    intensity: 0.85,
    position: [0, 12, -22],
    atmosphere: {
      fogDensity: 0.028,
      blurAmount: 2.5,
      bloomIntensity: 1.7,
    },
    lightingPreset: {
      ambient: '#12123b',
      directional: '#c7d2fe',
      pointIntensity: 2.4,
    },
    particlePreset: {
      count: 1150,
      speed: 0.025,
      size: 0.23,
      motionType: 'orbit',
      color: '#e0e7ff',
    },
    cameraPreset: {
      fov: 52,
      distance: 25,
      damping: 0.04,
    },
    compatibleGenres: ['Mystery', 'Neo-Noir', 'Crime', 'Sci-Fi'],
    compatibleThemes: ['Uncovering Truth', 'Hidden Secrets', 'Complex Puzzles', 'Double Identities'],
    compatiblePacing: 'Slow',
    compatibleVisualStyles: ['Twilight Shadows', 'Subtle Venetian Blinds', 'Atmospheric Fog'],
  },
  {
    id: 'reflection',
    name: 'Reflection',
    tagline: 'Crystalline contemplative quiet and deep meditation',
    description: 'Deep indigo mirror plane, crystalline stillness, and meditative rhythmic pulses.',
    color: '#38bdf8',
    accentColor: '#0284c7',
    fogColor: '#030e17',
    intensity: 0.65,
    position: [10, -8, -16],
    atmosphere: {
      fogDensity: 0.022,
      blurAmount: 2.8,
      bloomIntensity: 1.0,
    },
    lightingPreset: {
      ambient: '#082f49',
      directional: '#bae6fd',
      pointIntensity: 1.5,
    },
    particlePreset: {
      count: 800,
      speed: 0.01,
      size: 0.2,
      motionType: 'float',
      color: '#e0f2fe',
    },
    cameraPreset: {
      fov: 46,
      distance: 23,
      damping: 0.02,
    },
    compatibleGenres: ['Drama', 'Art House', 'Philosophical', 'Biography'],
    compatibleThemes: ['Existential Questions', 'Self-Examination', 'Nature & Humanity', 'Silence'],
    compatiblePacing: 'Slow',
    compatibleVisualStyles: ['Symmetrical Compositions', 'Reflective Surfaces', 'Unbroken Long Takes'],
  },
  {
    id: 'curiosity',
    name: 'Curiosity',
    tagline: 'Playful intrigue, shifting geometries, and active discovery',
    description: 'Ethereal shifting geometries, curious pulsing nodes, and playful particle orbits.',
    color: '#2dd4bf',
    accentColor: '#0d9488',
    fogColor: '#021815',
    intensity: 0.8,
    position: [-10, -4, -14],
    atmosphere: {
      fogDensity: 0.015,
      blurAmount: 1.8,
      bloomIntensity: 1.6,
    },
    lightingPreset: {
      ambient: '#042f2e',
      directional: '#99f6e4',
      pointIntensity: 2.2,
    },
    particlePreset: {
      count: 1050,
      speed: 0.04,
      size: 0.22,
      motionType: 'orbit',
      color: '#ccfbf1',
    },
    cameraPreset: {
      fov: 54,
      distance: 22,
      damping: 0.05,
    },
    compatibleGenres: ['Sci-Fi', 'Documentary', 'Mystery', 'Adventure'],
    compatibleThemes: ['Scientific Discovery', 'Unlocking Secrets', 'Unfamiliar Cultures', 'Innovation'],
    compatiblePacing: 'Moderate',
    compatibleVisualStyles: ['Macro Close-ups', 'Intricate Diagrams', 'Bright Dynamic Lighting'],
  },
  {
    id: 'escapism',
    name: 'Escapism',
    tagline: 'Dreamlike fantasy landscapes and prismatic refractions',
    description: 'Prismatic light refractions, ethereal floating horizon, and surreal dream state.',
    color: '#a78bfa',
    accentColor: '#7c3aed',
    fogColor: '#110926',
    intensity: 0.88,
    position: [5, -14, -21],
    atmosphere: {
      fogDensity: 0.018,
      blurAmount: 2.2,
      bloomIntensity: 1.8,
    },
    lightingPreset: {
      ambient: '#2e1065',
      directional: '#ddd6fe',
      pointIntensity: 2.6,
    },
    particlePreset: {
      count: 1250,
      speed: 0.03,
      size: 0.26,
      motionType: 'drift',
      color: '#ede9fe',
    },
    cameraPreset: {
      fov: 62,
      distance: 27,
      damping: 0.04,
    },
    compatibleGenres: ['Fantasy', 'Animation', 'Adventure', 'Sci-Fi'],
    compatibleThemes: ['Parallel Worlds', 'Unbound Imagination', 'Magic Realism', 'Heroic Journeys'],
    compatiblePacing: 'Moderate',
    compatibleVisualStyles: ['Lush Saturated Landscapes', 'Surreal Physics', 'Painterly Color Spaces'],
  },
  {
    id: 'inspiration',
    name: 'Inspiration',
    tagline: 'Uplifting warmth and ascending beams of triumph',
    description: 'Ascending beam of brilliant warm white/gold, radiant aura, and uplifting drift.',
    color: '#eab308',
    accentColor: '#ca8a04',
    fogColor: '#1a1303',
    intensity: 0.9,
    position: [0, 14, -18],
    atmosphere: {
      fogDensity: 0.014,
      blurAmount: 1.8,
      bloomIntensity: 2.1,
    },
    lightingPreset: {
      ambient: '#3a2002',
      directional: '#fef08a',
      pointIntensity: 3.2,
    },
    particlePreset: {
      count: 1400,
      speed: 0.045,
      size: 0.27,
      motionType: 'ascend',
      color: '#fef9c3',
    },
    cameraPreset: {
      fov: 56,
      distance: 25,
      damping: 0.04,
    },
    compatibleGenres: ['Biography', 'Sports', 'Drama', 'Adventure'],
    compatibleThemes: ['Overcoming Odds', 'Human Potential', 'Artistic Calling', 'Triumph of Spirit'],
    compatiblePacing: 'Moderate',
    compatibleVisualStyles: ['Soaring Aerial Views', 'Golden Backlighting', 'Heroic Framing'],
  },
];
